DROP DATABASE IF EXISTS  staffmanager;
CREATE DATABASE staffmanager;
USE staffmanager;
DROP TABLE IF EXISTS staff;
CREATE TABLE staff(id BIGINT PRIMARY KEY AUTO_INCREMENT,NAME VARCHAR(20),card_id BIGINT,work_id BIGINT,sex INT,birth_date VARCHAR(10),certificate_no VARCHAR(20),edu_level_id bigint,edu_level VARCHAR(10),phone VARCHAR(20), address VARCHAR(50),profession_id BIGINT, profession VARCHAR(20),department_id BIGINT,dep1_id bigint,dep2_id bigint,dep3_id bigint,department VARCHAR(20),clazz_id BIGINT,clazz VARCHAR(20),image BLOB);
DROP TABLE IF EXISTS info_item;
CREATE TABLE info_item(id BIGINT PRIMARY KEY AUTO_INCREMENT,`name` VARCHAR(20),`type` INT,VALUE VARCHAR(20),LEVEL INT DEFAULT 1,parent_id BIGINT DEFAULT 0,description VARCHAR(200));
DROP TABLE IF EXISTS sub_device;
CREATE TABLE sub_device(id BIGINT AUTO_INCREMENT PRIMARY KEY,`name` VARCHAR(20),state INT ,type_id BIGINT,`type` VARCHAR(20),region_id BIGINT,region VARCHAR(50),description VARCHAR(100));
DROP TABLE IF EXISTS card_reader;
CREATE TABLE card_reader(id BIGINT AUTO_INCREMENT PRIMARY KEY,device_id BIGINT,port_num INT,`name` VARCHAR(20),state INT ,type_id BIGINT,`type` VARCHAR(20),region_id BIGINT,region VARCHAR(50),description VARCHAR(100));
DROP TABLE IF EXISTS USER;
CREATE TABLE USER(id BIGINT PRIMARY KEY AUTO_INCREMENT,NAME VARCHAR(20),pwd VARCHAR(20),priv INT );
DROP TABLE IF EXISTS position_log;
CREATE TABLE position_log(id BIGINT AUTO_INCREMENT PRIMARY KEY,card_id BIGINT,sub_device_id BIGINT,reader_id BIGINT,arrive_time BIGINT,stay_time BIGINT);
#保存每个标识卡的最新位置
DROP TABLE IF EXISTS card_newest_position_;
CREATE TABLE card_newest_position_(card_id BIGINT PRIMARY KEY,sub_device_id BIGINT,reader_id BIGINT);
INSERT INTO info_item(NAME,TYPE,VALUE,LEVEL)  VALUES( "部门",2,"组织结构",0);
INSERT INTO info_item(NAME,TYPE,VALUE,LEVEL,parent_id)  VALUES( "部门",2,"部门1",1,1);
INSERT INTO info_item(NAME,TYPE,VALUE,LEVEL,parent_id)  VALUES( "部门",2,"部门2",1,1);
INSERT INTO info_item(NAME,TYPE,VALUE,LEVEL,parent_id)  VALUES( "部门",2,"部门3",1,1);
INSERT INTO info_item(NAME,TYPE,VALUE,LEVEL,parent_id)  VALUES( "部门",2,"部门11",2,2);
INSERT INTO info_item(NAME,TYPE,VALUE,LEVEL,parent_id)  VALUES( "部门",2,"部门21",2,3);
INSERT INTO info_item(NAME,TYPE,VALUE,LEVEL,parent_id)  VALUES( "部门",2,"部门31",2,4);
INSERT INTO info_item(NAME,TYPE,VALUE)  VALUES( "教育程度",0,"请选择");
INSERT INTO info_item(NAME,TYPE,VALUE)  VALUES( "教育程度",0,"高中");
INSERT INTO info_item(NAME,TYPE,VALUE)  VALUES( "教育程度",0,"大学");
INSERT INTO info_item(NAME,TYPE,VALUE)  VALUES( "教育程度",0,"硕士");
INSERT INTO info_item(NAME,TYPE,VALUE)  VALUES( "工种",1,"请选择");
INSERT INTO info_item(NAME,TYPE,VALUE)  VALUES( "工种",1,"工种1");
INSERT INTO info_item(NAME,TYPE,VALUE)  VALUES( "工种",1,"工种2");
INSERT INTO info_item(NAME,TYPE,VALUE)  VALUES( "工种",1,"工种3");
INSERT INTO info_item(NAME,TYPE,VALUE)  VALUES( "班组",3,"请选择");
INSERT INTO info_item(NAME,TYPE,VALUE)  VALUES( "班组",3,"8点");
INSERT INTO info_item(NAME,TYPE,VALUE)  VALUES( "班组",3,"16点");
INSERT INTO info_item(NAME,TYPE,VALUE)  VALUES( "班组",3,"0点");
INSERT INTO info_item(NAME,TYPE,VALUE)  VALUES( "区域",4,"请选择");
INSERT INTO info_item(NAME,TYPE,VALUE)  VALUES( "区域",4,"区域1");
INSERT INTO info_item(NAME,TYPE,VALUE)  VALUES( "区域",4,"区域2");
INSERT INTO info_item(NAME,TYPE,VALUE)  VALUES( "分站类型",5,"请选择");
INSERT INTO info_item(NAME,TYPE,VALUE)  VALUES( "分站类型",5,"分站类型1");
INSERT INTO info_item(NAME,TYPE,VALUE)  VALUES( "分站类型",5,"分站类型2");
INSERT INTO info_item(NAME,TYPE,VALUE)  VALUES( "读卡器类型",6,"请选择");
INSERT INTO info_item(NAME,TYPE,VALUE)  VALUES( "读卡器类型",6,"读卡器类型1");
INSERT INTO info_item(NAME,TYPE,VALUE)  VALUES( "读卡器类型",6,"读卡器类型2");
INSERT INTO USER(NAME,pwd,priv) VALUES("admin","admin",1);